//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhachSan.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class tbl_room_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_room_type()
        {
            this.tbl_room = new HashSet<tbl_room>();
        }

        [Display(Name = "RoomTypeId")]
        public int room_type_id { get; set; }
        [Display(Name = "RoomName")]
        public string room_name { get; set; }
        [Display(Name = "Description")]
        public string description { get; set; }
        [Display(Name = "RoomPrice")]
        public Nullable<decimal> room_price { get; set; }
        [Display(Name = "RoomCapacity")]
        public byte room_capacity { get; set; }
        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Room")]
        public virtual ICollection<tbl_room> tbl_room { get; set; }
    }
}
