//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhachSan.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_user
    {
        [Display(Name = "UserId")]
        public int userid { get; set; }
        [Display(Name = "UserName")]
        public string username { get; set; }
        [Display(Name = "Email")]
        public string email { get; set; }
        [Display(Name = "UserPassword")]
        public string user_password { get; set; }
        [Display(Name = "UserLevel")]
        public int user_level { get; set; }
        [Display(Name = "UserLevel")]

        public virtual tbl_user_level tbl_user_level { get; set; }
    }
}
